dns:
  ttl: 150
  port: 5311
  host: 127.0.0.1
  default: 8.8.8.8

  records:
    google.com:
      type: A
      address: 127.0.0.1

    example.com:
      type: A
      address: 127.0.0.1

proxy:
  port:
    - 80
    - 81
    - 8080
    - 8081
    - 3000
    - 5000
    - 443
  host: 127.0.0.1
  time_to_alive: 10