default_dns: 8.8.8.8

dns_server:
  ttl: 150
  port: 5311
  host: 127.0.0.1

proxy_server:
  port: 443
  host: 127.0.0.1
  time_to_alive: 10

records:
  google.com:
    type: A
    address: 127.0.0.1

  example.com:
    type: A
    address: 127.0.0.1